# Set your default shell (if so desired)
set -g default-shell /bin/zsh

# Setting the prefix from C-b to C-a
set -g prefix C-a

# Free the original Ctrl-b prefix keybinding
unbind C-b

#reduce the default delay between prefix and command
set -s escape-time 1

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
# setw is short for 'set-window-option'
setw -g pane-base-index 1

# reload the tmux configuration file with prefix r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Ensure that we can send Ctrl-A to other apps
bind C-a send-prefix

# splitting panes with | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
# split pane and retain the current directory of existing pane
# bind _ split-window -v -c "#{pane_current_path}"
# bind \ split-window -h -c "#{pane_current_path}"

# moving between panes with Prefix h,j,k,l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Quick window selection
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# resize paes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# default is 500
set-option -g repeat-time 750

# mouse support - set to on if you want to use the mouse
set -g mouse off

# Set the default terminal mode to 256color mode
set -g default-terminal "screen-256color"

# set the status line's colors
set -g status-style fg=white,bg=black

# set the color of the window list
setw -g window-status-style fg=cyan,bg=black

# set colors for the active window
setw -g window-status-current-style fg=cyan,bold,bg=black

# colors for pane borders
setw -g pane-border-style fg=green,bg=black
setw -g pane-active-border-style fg=white,bg=yellow

# active pane normal, other shaded out
setw -g window-style fg=colour240,bg=colour235
setw -g window-active-style fg=white,bg=black

# Command / message line
set -g message-style fg=white,bold,bg=black


# Status line left side to show [session] window# pane#
set -g status-left-length 80
# set -g status-left "#[fg=green][#S] #[fg=yellow]#I #[fg=cyan]#P"
set -g status-left '#[fg=green][#S] #[fg=yellow]#I #[fg=cyan]#P #(gitmux "#{pane_current_path}")'

# Status line right side -  13:37 31-Oct
set -g status-right "#[fg=cyan]%R %d %b"

# Center the window list in the status line
set -g status-justify centre

# enable activity alerts
# highlight the window name
setw -g monitor-activity on
# show an alert message in bar
set -g visual-activity off

# enable vi keys.
setw -g mode-keys vi

# Vim-like settings for buffer copy-paste
bind Escape copy-mode
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection
unbind p
bind p paste-buffer

if-shell "uname | grep -q Darwin" "source-file ~/dotfiles/tmux.mac.conf"
if-shell "uname | grep -q Linux" "source-file ~/dotfiles/tmux.linux.conf"

# shortcut for synchronize-panes toggle
bind C-x set-window-option synchronize-panes
#
# Log output to a text file on demand
bind P pipe-pane -o "cat >>~/#W.log" \; display "Toggled logging to ~/#W.log"

# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
run '~/.tmux/plugins/tpm/tpm'

